### PR TITLE
Test center firebase connection

### PR DESCRIPTION
**Pull request by J4yM1l**
test-center connected to firebase and populates the table with data from firebase.

### CODE REVIEW

**Review by bascoe10 — APPROVED** [review]

**Comment by J4yM1l** [comment]
Test center component is been connected to firebase and all its data are been fetched in real time from database.

**Comment by ernestkamara** [comment]
Isn’t this a duplicate of #26?

**Comment by J4yM1l** [comment]
@ernestkamara -hospitaName field has been added to test-center table and is production ready. You can populate test center table using admin form.  P.S. Current info displayed on the table are not accurate data. Needs to be updated with correct info.

**Comment by ernestkamara** [comment]
> @ernestkamara -hospitaName field has been added to test-center table and is production ready. You can populate test center table using admin form. P.S. Current info displayed on the table are not accurate data. Needs to be updated with correct info.

If that's the case you would have to merge the PR #26 and rebase develop into this branch to remove duplicates. Hope I'm not missing something.

**Review by ernestkamara — CHANGES_REQUESTED** [review]
See comment above!

**Pull request closed without merging**
